In [142]:
import pandas as pd

In [143]:
data = pd.read_csv('ai_job_market_dataset.csv')
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
1065,813,Machine Learning Engineer,Enterprise,Australia,Mid,Automotive,MLOps,Any,Internship,111962.0,True
1066,465,AI Engineer,SME,UK,Junior,Healthcare,TensorFlow,PhD,Contract,61936.0,True
1067,817,Machine Learning Engineer,SME,India,Lead,Finance,Deep Learning,PhD,Full-time,67837.0,False
1068,529,Data Scientist,Startup,UK,Lead,Finance,Statistics,Any,Part-time,79222.0,False
1069,18,Robotics Engineer,Startup,Germany,Mid,Automotive,SQL,PhD,Internship,61462.0,True

In [144]:
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
1065,813,Machine Learning Engineer,Enterprise,Australia,Mid,Automotive,MLOps,Any,Internship,111962.0,True
1066,465,AI Engineer,SME,UK,Junior,Healthcare,TensorFlow,PhD,Contract,61936.0,True
1067,817,Machine Learning Engineer,SME,India,Lead,Finance,Deep Learning,PhD,Full-time,67837.0,False
1068,529,Data Scientist,Startup,UK,Lead,Finance,Statistics,Any,Part-time,79222.0,False
1069,18,Robotics Engineer,Startup,Germany,Mid,Automotive,SQL,PhD,Internship,61462.0,True

In [145]:
data.shape

(1070, 11)

In [146]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1070 entries, 0 to 1069
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_id              1070 non-null   int64
 1   job_title           1070 non-null   object
 2   company_size        1070 non-null   object
 3   location            966 non-null    object
 4   experience_level    1070 non-null   object
 5   industry            966 non-null    object
 6   primary_skill       966 non-null    object
 7   education_required  966 non-null    object
 8   employment_type     1070 non-null   object
 9   salary_usd          966 non-null    float64
 10  remote_allowed      1070 non-null   bool
dtypes: bool(1), float64(1), int64(1), object(8)
memory usage: 84.8+ KB

In [147]:
data.describe()

            job_id     salary_usd
count  1070.000000     966.000000
mean    499.085981  128998.124224
std     288.387764   40571.822164
min       1.000000   60060.000000
25%     250.250000   93564.500000
50%     498.500000  129162.500000
75%     745.000000  165293.000000
max    1000.000000  199810.000000

In [148]:
data.duplicated().sum()

np.int64(70)

In [149]:
data.drop_duplicates(inplace = True)

In [150]:
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,NaN,Lead,NaN,NaN,NaN,Internship,NaN,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [151]:
data.shape

(1000, 11)

In [152]:
data.isnull().sum()

job_id                  0
job_title               0
company_size            0
location              100
experience_level        0
industry              100
primary_skill         100
education_required    100
employment_type         0
salary_usd            100
remote_allowed          0
dtype: int64

In [153]:
data['location'].value_counts()

location
UK           128
Canada       124
India        122
USA          112
Remote       112
Singapore    103
Australia    103
Germany       96
Name: count, dtype: int64

In [154]:
data.isnull().sum().sum()

np.int64(500)

In [155]:
list(data.columns[data.isnull().any()])

['location', 'industry', 'primary_skill', 'education_required', 'salary_usd']

In [156]:
data['location'].mode()

0    UK
Name: location, dtype: object

In [157]:
data['location'] = data['location'].fillna(data['location'].mode()[0])
data['location']

0             UK
1          India
2          India
3            USA
4         Canada
         ...
995           UK
996    Singapore
997           UK
998           UK
999    Singapore
Name: location, Length: 1000, dtype: object

In [158]:
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,UK,Lead,NaN,NaN,NaN,Internship,NaN,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [159]:
list(data.columns[data.isnull().any()])

['industry', 'primary_skill', 'education_required', 'salary_usd']

In [160]:
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,UK,Lead,NaN,NaN,NaN,Internship,NaN,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [161]:
data.isnull().sum()

job_id                  0
job_title               0
company_size            0
location                0
experience_level        0
industry              100
primary_skill         100
education_required    100
employment_type         0
salary_usd            100
remote_allowed          0
dtype: int64

In [162]:
data['location'].value_counts()

location
UK           228
Canada       124
India        122
USA          112
Remote       112
Singapore    103
Australia    103
Germany       96
Name: count, dtype: int64

In [163]:
data['industry'].mode()

0    Healthcare
Name: industry, dtype: object

In [164]:
data['industry']=data['industry'].fillna(data['industry'].mode()[0])
data['industry']

0         Automotive
1            Finance
2            Finance
3             Gaming
4             Gaming
           ...
995          Finance
996           Gaming
997       Healthcare
998       Healthcare
999    Cybersecurity
Name: industry, Length: 1000, dtype: object

In [165]:
data.isnull().sum()

job_id                  0
job_title               0
company_size            0
location                0
experience_level        0
industry                0
primary_skill         100
education_required    100
employment_type         0
salary_usd            100
remote_allowed          0
dtype: int64

In [166]:
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,UK,Lead,Healthcare,NaN,NaN,Internship,NaN,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [167]:
data['primary_skill'] = data['primary_skill'].fillna(data['primary_skill'].mode()[0])
data['primary_skill']

0             Python
1              MLOps
2                NLP
3      Deep Learning
4         Statistics
           ...
995              NLP
996       TensorFlow
997              NLP
998              NLP
999            MLOps
Name: primary_skill, Length: 1000, dtype: object

In [168]:
data.columns[data.isnull().any()]

Index(['education_required', 'salary_usd'], dtype='object')

In [169]:
data['education_required'].mode()

0    Any
Name: education_required, dtype: object

In [170]:
data['education_required']=data['education_required'].fillna(data['education_required'].mode()[0])
data['education_required']

0           PhD
1           Any
2        Master
3      Bachelor
4        Master
         ...
995    Bachelor
996         PhD
997         Any
998         Any
999         Any
Name: education_required, Length: 1000, dtype: object

In [171]:
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,UK,Lead,Healthcare,NLP,Any,Internship,NaN,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [172]:
data.isnull().sum()

job_id                  0
job_title               0
company_size            0
location                0
experience_level        0
industry                0
primary_skill           0
education_required      0
employment_type         0
salary_usd            100
remote_allowed          0
dtype: int64

In [173]:
data['salary_usd'].median()

130767.5

In [174]:
data['salary_usd'].median()

130767.5

In [175]:
data['salary_usd'] = data['salary_usd'].fillna(data['salary_usd'].median())
data['salary_usd']

0       91186.0
1       86928.0
2      182990.0
3      147029.0
4       80711.0
         ...
995    182961.0
996    164672.0
997     86639.0
998    130767.5
999    116677.0
Name: salary_usd, Length: 1000, dtype: float64

In [176]:
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,UK,Lead,Healthcare,NLP,Any,Internship,130767.5,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [177]:
data.isnull().sum()

job_id                0
job_title             0
company_size          0
location              0
experience_level      0
industry              0
primary_skill         0
education_required    0
employment_type       0
salary_usd            0
remote_allowed        0
dtype: int64

In [178]:
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,UK,Lead,Healthcare,NLP,Any,Internship,130767.5,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [179]:
data = data[data['salary_usd'] >0]
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,UK,Lead,Healthcare,NLP,Any,Internship,130767.5,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [180]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_id              1000 non-null   int64
 1   job_title           1000 non-null   object
 2   company_size        1000 non-null   object
 3   location            1000 non-null   object
 4   experience_level    1000 non-null   object
 5   industry            1000 non-null   object
 6   primary_skill       1000 non-null   object
 7   education_required  1000 non-null   object
 8   employment_type     1000 non-null   object
 9   salary_usd          1000 non-null   float64
 10  remote_allowed      1000 non-null   bool
dtypes: bool(1), float64(1), int64(1), object(8)
memory usage: 86.9+ KB

In [181]:
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   job_id              1000 non-null   int64
 1   job_title           1000 non-null   object
 2   company_size        1000 non-null   object
 3   location            1000 non-null   object
 4   experience_level    1000 non-null   object
 5   industry            1000 non-null   object
 6   primary_skill       1000 non-null   object
 7   education_required  1000 non-null   object
 8   employment_type     1000 non-null   object
 9   salary_usd          1000 non-null   float64
 10  remote_allowed      1000 non-null   bool
dtypes: bool(1), float64(1), int64(1), object(8)
memory usage: 86.9+ KB

job_id                0
job_title             0
company_size          0
location              0
experience_level      0
industry              0
primary_skill         0
education_required    0
employment_type       0
salary_usd            0
remote_allowed        0
dtype: int64

In [182]:
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,UK,Lead,Healthcare,NLP,Any,Internship,130767.5,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [183]:
data.to_csv('cleaned_ai_job_market',index=False)

In [203]:
import pandas as pd
from sqlalchemy import create_engine

In [204]:
import pandas as pd
data =pd.read_csv('cleaned_ai_job_market')
data

,job_id,job_title,company_size,location,experience_level,industry,primary_skill,education_required,employment_type,salary_usd,remote_allowed
0,1,Data Analyst,SME,UK,Mid,Automotive,Python,PhD,Internship,91186.0,True
1,2,AI Engineer,Enterprise,India,Junior,Finance,MLOps,Any,Full-time,86928.0,False
2,3,NLP Engineer,Startup,India,Senior,Finance,NLP,Master,Contract,182990.0,False
3,4,Data Analyst,Startup,USA,Lead,Gaming,Deep Learning,Bachelor,Internship,147029.0,False
4,5,AI Researcher,Startup,Canada,Senior,Gaming,Statistics,Master,Full-time,80711.0,False
...,...,...,...,...,...,...,...,...,...,...,...
995,996,NLP Engineer,SME,UK,Junior,Finance,NLP,Bachelor,Full-time,182961.0,True
996,997,Machine Learning Engineer,SME,Singapore,Senior,Gaming,TensorFlow,PhD,Contract,164672.0,True
997,998,AI Engineer,SME,UK,Junior,Healthcare,NLP,Any,Part-time,86639.0,True
998,999,Robotics Engineer,Startup,UK,Lead,Healthcare,NLP,Any,Internship,130767.5,False
999,1000,AI Researcher,Startup,Singapore,Junior,Cybersecurity,MLOps,Any,Contract,116677.0,False

In [205]:
engine = create_engine('mysql+mysqlconnector://root:2000@localhost:3306/ai_job_market_db')
data.to_sql(name = 'ai_job_market_db',con=engine,if_exists = 'replace',index = 'False')

1000

In [206]:
test_data = pd.read_sql('select * from ai_job_market_db LIMIT 5',engine)
print(test_data)

   False  job_id      job_title company_size location experience_level  \
0      0       1   Data Analyst          SME       UK              Mid
1      1       2    AI Engineer   Enterprise    India           Junior
2      2       3   NLP Engineer      Startup    India           Senior
3      3       4   Data Analyst      Startup      USA             Lead
4      4       5  AI Researcher      Startup   Canada           Senior

     industry  primary_skill education_required employment_type  salary_usd  \
0  Automotive         Python                PhD      Internship     91186.0
1     Finance          MLOps                Any       Full-time     86928.0
2     Finance            NLP             Master        Contract    182990.0
3      Gaming  Deep Learning           Bachelor      Internship    147029.0
4      Gaming     Statistics             Master       Full-time     80711.0

   remote_allowed
0               1
1               0
2               0
3               0
4               0